name: Deploy To S3

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
  

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: [2.5]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}

    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: gems-${{ runner.os }}-${{ matrix.ruby-version }}-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          gems-${{ runner.os }}-${{ matrix.ruby-version }}-
          gems-${{ runner.os }}-

    # necessary to get ruby 2.3 to work nicely with bundler vendor/bundle cache
    # can remove once ruby 2.3 is no longer supported
    - run: gem update --system
    - run: bundle config set deployment 'true'
    - name: bundle install
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3

    - run: |
        bundle exec middleman build
    # - name: List files in the repository
    #   run: |
    #     ls ${{ github.workspace }}
    - name: Changelog
      uses: scottbrenner/generate-changelog-action@master
      id: Changelog

    - uses: actions/upload-artifact@v2
      with: 
        name: staticFiles
        path: /home/runner/work/changer-docs/changer-docs/build/

    - name: Deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws s3 cp \
          --recursive \
          --region ap-northeast-2 \
          /home/runner/work/changer-docs/changer-docs/build/ s3://cefi-api-example

    - name: Bump Version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Create a GitHub release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: Release ${{ steps.tag_version.outputs.new_tag }}
        body: |
          ${{ steps.Changelog.outputs.changelog }}

